FROM php:7.4-fpm

# Variables
ENV WORKDIR=/var/www/html
ENV FILES_PATH=web-crud

########################################################################################################################
# Install packages
########################################################################################################################
## Missing xls and intl
RUN apt-get update && apt-get install -y \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev && apt-get install vim -y && apt-get install -y libzip-dev git wget --no-install-recommends zip \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh' | bash
RUN apt install symfony-cli

RUN symfony server:ca:install

RUN apt-get install -y zip unzip

# Postgres
RUN apt-get install -y libpq-dev
RUN docker-php-ext-install pdo_pgsql




# Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
# RUN composer install --no-interaction

COPY ./docker/crud.ett.loc.conf /etc/apache2/sites-enabled/
WORKDIR ${WORKDIR}

CMD php-fpm

# CMD ["apache2-foreground"]

EXPOSE 80